apiVersion: v1
kind: Service
metadata:
  name: consumeriq-translator
  namespace: consumeriq
spec:
  type: ClusterIP
  selector:
    app: consumeriq-translator
  ports:
    - name: http
      port: 8080
      targetPort: 8080
