from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Any


def _envName(endpoint_key: str) -> str:
    normalized = endpoint_key.upper().replace('.', '_').replace('-', '_')
    return f'BRIGHTDATA_DATASET_{normalized}'


@dataclass(frozen=True)
class BrightDataEndpoint:
    key: str
    label: str
    dataset_key: str | None
    dataset_id: str | None = None
    marketplace: str | None = None
    scrape_type: str | None = None
    discover_by: str | None = None
    required_fields: tuple[str, ...] = ()
    optional_fields: tuple[str, ...] = ()
    default_input: dict[str, Any] = field(default_factory=dict)
    notes: str | None = None
    env_name: str | None = None

    def resolved_dataset_id(self) -> str | None:
        env_name = self.env_name or _envName(self.key)
        return os.getenv(env_name) or self.dataset_id

    def public_dict(self) -> dict[str, Any]:
        env_name = self.env_name or _envName(self.key)
        return {
            'key': self.key,
            'label': self.label,
            'marketplace': self.marketplace,
            'datasetKey': self.dataset_key,
            'datasetId': self.dataset_id,
            'datasetIdEnv': env_name,
            'configured': bool(self.resolved_dataset_id()),
            'type': self.scrape_type,
            'discoverBy': self.discover_by,
            'requiredFields': list(self.required_fields),
            'optionalFields': list(self.optional_fields),
            'defaultInput': self.default_input,
            'notes': self.notes,
        }


BRIGHTDATA_ENDPOINTS: dict[str, BrightDataEndpoint] = {
    'tokopedia.products.collect_url': BrightDataEndpoint(
        key='tokopedia.products.collect_url',
        label='Tokopedia Products - collect by URL',
        marketplace='tokopedia',
        dataset_key='tokopedia.products',
        dataset_id='gd_lxk24yba297r8qd3tp',
        required_fields=('url',),
    ),
    'tokopedia.products.discover_category_url': BrightDataEndpoint(
        key='tokopedia.products.discover_category_url',
        label='Tokopedia Products - discover by category URL',
        marketplace='tokopedia',
        dataset_key='tokopedia.products',
        dataset_id='gd_lxk24yba297r8qd3tp',
        required_fields=('url',),
        notes='Bright Data example uses the base scrape endpoint with a category/store URL input.',
    ),
    'tokopedia.products.discover_keyword': BrightDataEndpoint(
        key='tokopedia.products.discover_keyword',
        label='Tokopedia Products - discover by keyword',
        marketplace='tokopedia',
        dataset_key='tokopedia.products',
        dataset_id='gd_lxk24yba297r8qd3tp',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword',),
        optional_fields=('sort_by',),
        default_input={'sort_by': ''},
    ),
    'tokopedia.products.discover_seller_url': BrightDataEndpoint(
        key='tokopedia.products.discover_seller_url',
        label='Tokopedia Products - discover by seller URL',
        marketplace='tokopedia',
        dataset_key='tokopedia.products',
        dataset_id='gd_lxk24yba297r8qd3tp',
        scrape_type='discover_new',
        discover_by='seller_url',
        required_fields=('url',),
        optional_fields=('sort_by',),
        default_input={'sort_by': ''},
    ),
    'alibaba.products.collect_url': BrightDataEndpoint(
        key='alibaba.products.collect_url',
        label='Alibaba - collect by URL',
        marketplace='alibaba',
        dataset_key='alibaba.products',
        dataset_id='gd_mljabfy23d62b7eqr',
        required_fields=('url',),
    ),
    'alibaba.products.discover_category_url': BrightDataEndpoint(
        key='alibaba.products.discover_category_url',
        label='Alibaba - discover by category URL',
        marketplace='alibaba',
        dataset_key='alibaba.products',
        dataset_id='gd_mljabfy23d62b7eqr',
        scrape_type='discover_new',
        discover_by='category_url',
        required_fields=('url',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'aliexpress.products.collect_url': BrightDataEndpoint(
        key='aliexpress.products.collect_url',
        label='AliExpress products - collect by URL',
        marketplace='aliexpress',
        dataset_key='aliexpress.products',
        dataset_id='gd_mlj9v75u1w1jvaxvwp',
        required_fields=('url',),
    ),
    'aliexpress.products.collect_category_url': BrightDataEndpoint(
        key='aliexpress.products.collect_category_url',
        label='AliExpress products - collect by category URL',
        marketplace='aliexpress',
        dataset_key='aliexpress.products',
        dataset_id='gd_mlj9v75u1w1jvaxvwp',
        required_fields=('url',),
    ),
    'sephora.products.collect_url': BrightDataEndpoint(
        key='sephora.products.collect_url',
        label='Sephora Products - collect by URL',
        marketplace='sephora',
        dataset_key='sephora.products',
        dataset_id='gd_mloyjmqz1ucoikm4ja',
        required_fields=('url',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'sephora.products.discover_sitemap': BrightDataEndpoint(
        key='sephora.products.discover_sitemap',
        label='Sephora Products - discover by sitemap',
        marketplace='sephora',
        dataset_key='sephora.products',
        dataset_id='gd_mloyjmqz1ucoikm4ja',
        scrape_type='discover_new',
        discover_by='sitemap',
        required_fields=('url',),
        optional_fields=('all_variations', 'url_pattern'),
        default_input={'all_variations': True, 'url_pattern': '/product/'},
    ),
    'etsy.products.collect_url': BrightDataEndpoint(
        key='etsy.products.collect_url',
        label='Etsy - collect by URL',
        marketplace='etsy',
        dataset_key='etsy.products',
        dataset_id='gd_ltppk0jdv1jqz25mz',
        required_fields=('url',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'etsy.products.discover_keyword': BrightDataEndpoint(
        key='etsy.products.discover_keyword',
        label='Etsy - discover by keyword',
        marketplace='etsy',
        dataset_key='etsy.products',
        dataset_id='gd_ltppk0jdv1jqz25mz',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'etsy.products.discover_shop_url': BrightDataEndpoint(
        key='etsy.products.discover_shop_url',
        label='Etsy - discover by shop URL',
        marketplace='etsy',
        dataset_key='etsy.products',
        dataset_id='gd_ltppk0jdv1jqz25mz',
        scrape_type='discover_new',
        discover_by='shop_url',
        required_fields=('url',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'lazada.products.search_gmv.collect_url': BrightDataEndpoint(
        key='lazada.products.search_gmv.collect_url',
        label='Lazada products search (GMV) - collect by URL',
        marketplace='lazada',
        dataset_key='lazada.products.search_gmv',
        dataset_id='gd_lwd9icor28eg4srnxi',
        required_fields=('url',),
    ),
    'lazada.reviews.collect_url': BrightDataEndpoint(
        key='lazada.reviews.collect_url',
        label='Lazada Reviews - collect by URL',
        marketplace='lazada',
        dataset_key='lazada.reviews',
        dataset_id='gd_lub6mys21lzcklkq1z',
        required_fields=('url',),
        optional_fields=('start_date', 'end_date'),
    ),
    'lazada.products.discover_category': BrightDataEndpoint(
        key='lazada.products.discover_category',
        label='Lazada Products - discover by category',
        marketplace='lazada',
        dataset_key='lazada.products',
        dataset_id='gd_lk14r4zxuiw2uxpk6',
        scrape_type='discover_new',
        discover_by='category',
        required_fields=('category_url',),
    ),
    'lazada.products.discover_keyword': BrightDataEndpoint(
        key='lazada.products.discover_keyword',
        label='Lazada Products - discover by keyword',
        marketplace='lazada',
        dataset_key='lazada.products',
        dataset_id='gd_lk14r4zxuiw2uxpk6',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword', 'domain'),
        optional_fields=('limit',),
    ),
    'lazada.products.discover_seller': BrightDataEndpoint(
        key='lazada.products.discover_seller',
        label='Lazada Products - discover by seller',
        marketplace='lazada',
        dataset_key='lazada.products',
        dataset_id='gd_lk14r4zxuiw2uxpk6',
        scrape_type='discover_new',
        discover_by='seller',
        required_fields=('url',),
    ),
    'amazon.products.collect_url': BrightDataEndpoint(
        key='amazon.products.collect_url',
        label='Amazon - collect by URL',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_l7q7dkf244hwjntr0',
        required_fields=('url',),
        optional_fields=('zipcode', 'language'),
        default_input={'zipcode': '', 'language': ''},
    ),
    'amazon.products.discover_best_sellers_url': BrightDataEndpoint(
        key='amazon.products.discover_best_sellers_url',
        label='Amazon - discover by Best Seller URL',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_l7q7dkf244hwjntr0',
        scrape_type='discover_new',
        discover_by='best_sellers_url',
        required_fields=('category_url',),
        optional_fields=('zipcode',),
        default_input={'zipcode': ''},
    ),
    'amazon.products.discover_category_url': BrightDataEndpoint(
        key='amazon.products.discover_category_url',
        label='Amazon - discover by Category URL',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_l7q7dkf244hwjntr0',
        scrape_type='discover_new',
        discover_by='category_url',
        required_fields=('url',),
        optional_fields=('sort_by', 'zipcode'),
        default_input={'sort_by': '', 'zipcode': ''},
    ),
    'amazon.products.discover_keyword': BrightDataEndpoint(
        key='amazon.products.discover_keyword',
        label='Amazon - discover by keyword',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_l7q7dkf244hwjntr0',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword',),
        optional_fields=('zipcode',),
        default_input={'zipcode': ''},
    ),
    'amazon.products.discover_upc': BrightDataEndpoint(
        key='amazon.products.discover_upc',
        label='Amazon - discover by UPC',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_l7q7dkf244hwjntr0',
        scrape_type='discover_new',
        discover_by='upc',
        optional_fields=('upc',),
    ),
    'amazon.products.search.collect_url': BrightDataEndpoint(
        key='amazon.products.search.collect_url',
        label='Amazon - collect by URL (Product search)',
        marketplace='amazon',
        dataset_key='amazon.products.search',
        dataset_id='gd_lwdb4vjm1ehb499uxs',
        required_fields=('keyword', 'url'),
        optional_fields=('pages_to_search',),
    ),
    'amazon.reviews.collect_url': BrightDataEndpoint(
        key='amazon.reviews.collect_url',
        label='Amazon - collect reviews by URL',
        marketplace='amazon',
        dataset_key='amazon.reviews',
        dataset_id='gd_le8e811kzy4ggddlq',
        required_fields=('url',),
        optional_fields=('reviews_to_not_include', 'max_reviews'),
        default_input={'reviews_to_not_include': []},
    ),
    'amazon.seller_info.collect_url': BrightDataEndpoint(
        key='amazon.seller_info.collect_url',
        label='Amazon - collect seller info by URL',
        marketplace='amazon',
        dataset_key='amazon.seller_info',
        dataset_id='gd_lhotzucw1etoe5iw1k',
        required_fields=('url',),
    ),
    'amazon.products.global.collect_url': BrightDataEndpoint(
        key='amazon.products.global.collect_url',
        label='Amazon - collect by URL (Product global dataset)',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_lwhideng15g8jg63s7',
        required_fields=('url',),
    ),
    'amazon.products.global.discover_brand': BrightDataEndpoint(
        key='amazon.products.global.discover_brand',
        label='Amazon - discover by brand (Product global dataset)',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_lwhideng15g8jg63s7',
        scrape_type='discover_new',
        discover_by='brand',
        required_fields=('url',),
    ),
    'amazon.products.global.discover_category_url': BrightDataEndpoint(
        key='amazon.products.global.discover_category_url',
        label='Amazon - discover by category URL (Product global dataset)',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_lwhideng15g8jg63s7',
        scrape_type='discover_new',
        discover_by='category_url',
        required_fields=('url',),
        optional_fields=('sort_by', 'zipcode', 'get_sponsored'),
        default_input={'sort_by': '', 'zipcode': ''},
    ),
    'amazon.products.global.discover_keywords': BrightDataEndpoint(
        key='amazon.products.global.discover_keywords',
        label='Amazon - discover by keywords (Product global dataset)',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_lwhideng15g8jg63s7',
        scrape_type='discover_new',
        discover_by='keywords',
        required_fields=('keywords', 'domain'),
        optional_fields=('pages_to_search', 'zipcode'),
        default_input={'zipcode': ''},
    ),
    'amazon.products.global.discover_seller': BrightDataEndpoint(
        key='amazon.products.global.discover_seller',
        label='Amazon - discover by seller (Product global dataset)',
        marketplace='amazon',
        dataset_key='amazon.products',
        dataset_id='gd_lwhideng15g8jg63s7',
        scrape_type='discover_new',
        discover_by='seller',
        required_fields=('url',),
    ),
    'walmart.products.collect_url': BrightDataEndpoint(
        key='walmart.products.collect_url',
        label='Walmart - collect by URL',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_l95fol7l1ru6rlo116',
        required_fields=('url',),
    ),
    'walmart.products.discover_category_url': BrightDataEndpoint(
        key='walmart.products.discover_category_url',
        label='Walmart - discover by category URL',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_l95fol7l1ru6rlo116',
        scrape_type='discover_new',
        discover_by='category_url',
        required_fields=('category_url',),
        optional_fields=('all_variations',),
        default_input={'all_variations': True},
    ),
    'walmart.products.discover_keyword': BrightDataEndpoint(
        key='walmart.products.discover_keyword',
        label='Walmart - discover by keyword',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_l95fol7l1ru6rlo116',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword', 'domain'),
        optional_fields=('all_variations',),
        default_input={'domain': 'https://www.walmart.com/', 'all_variations': True},
    ),
    'walmart.products.discover_sku': BrightDataEndpoint(
        key='walmart.products.discover_sku',
        label='Walmart - discover by SKU',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_l95fol7l1ru6rlo116',
        scrape_type='discover_new',
        discover_by='sku',
        required_fields=('sku',),
    ),
    'walmart.products.search.collect_url': BrightDataEndpoint(
        key='walmart.products.search.collect_url',
        label='Walmart products search - collect by URL',
        marketplace='walmart',
        dataset_key='walmart.products.search',
        dataset_id='gd_m7khey0wb7wviejgj',
        required_fields=('url',),
    ),
    'walmart.products.zipcodes.collect_url': BrightDataEndpoint(
        key='walmart.products.zipcodes.collect_url',
        label='Walmart products zipcodes - collect by URL',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_m693oc1r1gebnayxq',
        required_fields=('url', 'zip_code', 'store_id'),
    ),
    'walmart.products.zipcodes.discover_category_url': BrightDataEndpoint(
        key='walmart.products.zipcodes.discover_category_url',
        label='Walmart products zipcodes - discover by category URL',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_m693oc1r1gebnayxq',
        scrape_type='discover_new',
        discover_by='category_url',
        required_fields=('url', 'zip_code'),
        optional_fields=('max_product', 'store_id', 'shipping_type'),
        default_input={'store_id': '', 'shipping_type': ''},
    ),
    'walmart.products.zipcodes.discover_keyword': BrightDataEndpoint(
        key='walmart.products.zipcodes.discover_keyword',
        label='Walmart products zipcodes - discover by keyword',
        marketplace='walmart',
        dataset_key='walmart.products',
        dataset_id='gd_m693oc1r1gebnayxq',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword', 'zip_code'),
        optional_fields=('store_id',),
        default_input={'store_id': ''},
    ),
    'walmart.seller_info.collect_url': BrightDataEndpoint(
        key='walmart.seller_info.collect_url',
        label='Walmart Seller Info - collect by URL',
        marketplace='walmart',
        dataset_key='walmart.seller_info',
        dataset_id='gd_m7ke48w81ocyu4hhz0',
        required_fields=('url',),
    ),
    'google.shopping.collect_url': BrightDataEndpoint(
        key='google.shopping.collect_url',
        label='Google Shopping - collect by URL',
        marketplace='google',
        dataset_key='google.shopping',
        dataset_id='gd_ltppk50q18kdw67omz',
        required_fields=('url',),
        optional_fields=('country',),
        default_input={'country': ''},
    ),
    'google.shopping.discover_keyword': BrightDataEndpoint(
        key='google.shopping.discover_keyword',
        label='Google Shopping - discover by keyword',
        marketplace='google',
        dataset_key='google.shopping',
        dataset_id='gd_ltppk50q18kdw67omz',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword',),
        optional_fields=('country',),
        default_input={'country': 'US'},
    ),
    'google.shopping.search_us.collect_url': BrightDataEndpoint(
        key='google.shopping.search_us.collect_url',
        label='Google Shopping products search US - collect by URL',
        marketplace='google',
        dataset_key='google.shopping.search_us',
        dataset_id='gd_m31f2k0d2m1bah4f3b',
        required_fields=('url',),
    ),
    'google.serp_100.collect_url': BrightDataEndpoint(
        key='google.serp_100.collect_url',
        label='Google SERP 100 Results - collect by URL',
        marketplace='google',
        dataset_key='google.serp_100',
        dataset_id='gd_mfz5x93lmsjjjylob',
        required_fields=('keyword',),
        optional_fields=(
            'url',
            'language',
            'country',
            'start_page',
            'end_page',
            'collapse_aio',
            'brd_mobile',
            'tbm',
            'uule',
            'tbs',
            'nfpr',
            'index',
            'include_paginated_html',
            'udm_web',
        ),
        default_input={
            'url': 'https://www.google.com/',
            'language': 'en',
            'country': 'US',
            'start_page': 1,
            'end_page': 10,
        },
        notes='Uses start_page=1 and end_page=10 by default for roughly top 100 organic results.',
    ),
    'google.ai_mode.collect_url': BrightDataEndpoint(
        key='google.ai_mode.collect_url',
        label='Google AI Mode Search - collect by URL',
        marketplace='google',
        dataset_key='google.ai_mode',
        dataset_id='gd_mcswdt6z2elth3zqr2',
        required_fields=('url', 'prompt'),
        optional_fields=('country',),
        default_input={'country': 'US'},
    ),
    'instagram.profiles.collect_url': BrightDataEndpoint(
        key='instagram.profiles.collect_url',
        label='Instagram - profiles by URL',
        marketplace='instagram',
        dataset_key='instagram.profiles',
        dataset_id='gd_l1vikfch901nx3by4',
        required_fields=('url',),
    ),
    'instagram.posts.collect_url': BrightDataEndpoint(
        key='instagram.posts.collect_url',
        label='Instagram - posts by URL',
        marketplace='instagram',
        dataset_key='instagram.posts',
        dataset_id='gd_lk5ns7kz21pck8jpis',
        required_fields=('url',),
    ),
    'instagram.reels.collect_url': BrightDataEndpoint(
        key='instagram.reels.collect_url',
        label='Instagram - reels by URL',
        marketplace='instagram',
        dataset_key='instagram.reels',
        dataset_id='gd_lyclm20il4r5helnj',
        required_fields=('url',),
    ),
    'instagram.comments.collect_url': BrightDataEndpoint(
        key='instagram.comments.collect_url',
        label='Instagram - comments by URL',
        marketplace='instagram',
        dataset_key='instagram.comments',
        dataset_id='gd_ltppn085pokosxh13',
        required_fields=('url',),
    ),
    'x.profiles.collect_url': BrightDataEndpoint(
        key='x.profiles.collect_url',
        label='X - profile by URL',
        marketplace='x',
        dataset_key='x.profiles',
        dataset_id='gd_lwxmeb2u1cniijd7t4',
        required_fields=('url',),
        optional_fields=('max_number_of_posts',),
    ),
    'x.posts.collect_url': BrightDataEndpoint(
        key='x.posts.collect_url',
        label='X - posts by URL',
        marketplace='x',
        dataset_key='x.posts',
        dataset_id='gd_lwxkxvnf1cynvib9co',
        required_fields=('url',),
    ),
    'x.posts.discover_profiles_array': BrightDataEndpoint(
        key='x.posts.discover_profiles_array',
        label='X - posts by profile array',
        marketplace='x',
        dataset_key='x.posts',
        dataset_id='gd_lwxkxvnf1cynvib9co',
        scrape_type='discover_new',
        discover_by='profiles_array',
        required_fields=('urls',),
        optional_fields=('start_date', 'end_date'),
        default_input={'start_date': '', 'end_date': ''},
    ),
    'x.posts.discover_profile_url_most_recent_posts': BrightDataEndpoint(
        key='x.posts.discover_profile_url_most_recent_posts',
        label='X - posts by profile URL most recent posts',
        marketplace='x',
        dataset_key='x.posts',
        dataset_id='gd_lwxkxvnf1cynvib9co',
        scrape_type='discover_new',
        discover_by='profile_url_most_recent_posts',
        required_fields=('url',),
        optional_fields=('start_date', 'end_date'),
        default_input={'start_date': '', 'end_date': ''},
    ),
    'tiktok.profiles.collect_url': BrightDataEndpoint(
        key='tiktok.profiles.collect_url',
        label='TikTok - profile by URL',
        marketplace='tiktok',
        dataset_key='tiktok.profiles',
        dataset_id='gd_l1villgoiiidt09ci',
        required_fields=('url',),
        optional_fields=('country',),
        default_input={'country': ''},
    ),
    'tiktok.profiles.discover_search_url': BrightDataEndpoint(
        key='tiktok.profiles.discover_search_url',
        label='TikTok - profiles discover by search URL',
        marketplace='tiktok',
        dataset_key='tiktok.profiles',
        dataset_id='gd_l1villgoiiidt09ci',
        scrape_type='discover_new',
        discover_by='search_url',
        required_fields=('search_url',),
        optional_fields=('country',),
        default_input={'country': ''},
    ),
    'tiktok.comments.collect_url': BrightDataEndpoint(
        key='tiktok.comments.collect_url',
        label='TikTok - comments by URL',
        marketplace='tiktok',
        dataset_key='tiktok.comments',
        dataset_id='gd_lkf2st302ap89utw5k',
        required_fields=('url',),
    ),
    'tiktok.posts.collect_url': BrightDataEndpoint(
        key='tiktok.posts.collect_url',
        label='TikTok - post by URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_lu702nij2f790tmv9h',
        required_fields=('url',),
        optional_fields=('country',),
        default_input={'country': ''},
    ),
    'tiktok.posts.discover_keyword': BrightDataEndpoint(
        key='tiktok.posts.discover_keyword',
        label='TikTok - posts by keyword',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_lu702nij2f790tmv9h',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('search_keyword',),
        optional_fields=('country',),
        default_input={'country': ''},
    ),
    'tiktok.posts.discover_profile_url': BrightDataEndpoint(
        key='tiktok.posts.discover_profile_url',
        label='TikTok - posts by profile URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_lu702nij2f790tmv9h',
        scrape_type='discover_new',
        discover_by='profile_url',
        required_fields=('url',),
        optional_fields=(
            'num_of_posts',
            'posts_to_not_include',
            'what_to_collect',
            'start_date',
            'end_date',
            'post_type',
            'country',
            'sort_by',
        ),
        default_input={
            'num_of_posts': 0,
            'what_to_collect': 'Posts & Reposts',
            'start_date': '',
            'end_date': '',
            'post_type': '',
            'country': '',
            'sort_by': '',
        },
    ),
    'tiktok.posts.discover_url': BrightDataEndpoint(
        key='tiktok.posts.discover_url',
        label='TikTok - posts discover by URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_lu702nij2f790tmv9h',
        scrape_type='discover_new',
        discover_by='url',
        required_fields=('URL',),
    ),
    'tiktok.profile_posts.collect_url': BrightDataEndpoint(
        key='tiktok.profile_posts.collect_url',
        label='TikTok - profile posts by URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_m7n5v2gq296pex2f5m',
        required_fields=('url',),
        optional_fields=('start_date', 'end_date'),
        default_input={'start_date': '', 'end_date': ''},
    ),
    'tiktok.discover_pages.collect_url': BrightDataEndpoint(
        key='tiktok.discover_pages.collect_url',
        label='TikTok - discover/channel/music page by URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_m736hjp71lejc5dc0l',
        required_fields=('url',),
        optional_fields=('start_date', 'end_date'),
        default_input={'start_date': '', 'end_date': ''},
    ),
    'tiktok.search_results.collect_url': BrightDataEndpoint(
        key='tiktok.search_results.collect_url',
        label='TikTok - search results by URL',
        marketplace='tiktok',
        dataset_key='tiktok.posts',
        dataset_id='gd_m7n5ixlw1gc4no56kx',
        required_fields=('url',),
        optional_fields=('country', 'num_of_posts'),
        default_input={'country': ''},
    ),
    'tiktok.shop.products.collect_url': BrightDataEndpoint(
        key='tiktok.shop.products.collect_url',
        label='TikTok Shop - product by URL',
        marketplace='tiktok_shop',
        dataset_key='tiktok.shop.products',
        dataset_id='gd_m45m1u911dsa4274pi',
        required_fields=('url',),
    ),
    'tiktok.shop.products.discover_category': BrightDataEndpoint(
        key='tiktok.shop.products.discover_category',
        label='TikTok Shop - discover by category',
        marketplace='tiktok_shop',
        dataset_key='tiktok.shop.products',
        dataset_id='gd_m45m1u911dsa4274pi',
        scrape_type='discover_new',
        discover_by='category',
        required_fields=('category_url',),
    ),
    'tiktok.shop.products.discover_keyword': BrightDataEndpoint(
        key='tiktok.shop.products.discover_keyword',
        label='TikTok Shop - discover by keyword',
        marketplace='tiktok_shop',
        dataset_key='tiktok.shop.products',
        dataset_id='gd_m45m1u911dsa4274pi',
        scrape_type='discover_new',
        discover_by='keyword',
        required_fields=('keyword', 'domain'),
    ),
    'tiktok.shop.products.discover_shop': BrightDataEndpoint(
        key='tiktok.shop.products.discover_shop',
        label='TikTok Shop - discover by shop',
        marketplace='tiktok_shop',
        dataset_key='tiktok.shop.products',
        dataset_id='gd_m45m1u911dsa4274pi',
        scrape_type='discover_new',
        discover_by='shop',
        required_fields=('url',),
    ),
    'tiktok.shop.category.collect_url': BrightDataEndpoint(
        key='tiktok.shop.category.collect_url',
        label='TikTok Shop - category listing by URL',
        marketplace='tiktok_shop',
        dataset_key='tiktok.shop.products',
        dataset_id='gd_mdr83qr42wd1wt7vm',
        required_fields=('url',),
    ),
}


def get_endpoint(key: str) -> BrightDataEndpoint | None:
    return BRIGHTDATA_ENDPOINTS.get(key)


def get_endpoint_registry() -> dict[str, Any]:
    return {'endpoints': [endpoint.public_dict() for endpoint in BRIGHTDATA_ENDPOINTS.values()]}


def validate_endpoint_input(endpoint: BrightDataEndpoint, input_records: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    for index, record in enumerate(input_records):
        for field_name in endpoint.required_fields:
            value = record.get(field_name)
            if value is None or value == '':
                errors.append(f'input[{index}].{field_name} is required for {endpoint.key}')
    return errors
